language: python
env:
  - PYTHON_VERSION=3.7 TENSORFLOW_VERSION=1.15.2
  - PYTHON_VERSION=3.7 TENSORFLOW_VERSION=2.0.0
  - PYTHON_VERSION=3.7 TENSORFLOW_VERSION=2.1.0
before_install:
  - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - sh Miniconda3-latest-Linux-x86_64.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
install:
  - conda create -n test --yes -c conda-forge python=$PYTHON_VERSION pip numpy scipy matplotlib pandas xarray dask pyyaml netcdf4 s3fs
  - source activate test
  - pip install tensorflow==$TENSORFLOW_VERSION
  - pip install pytest
  - pip install .
  - python download_data.py
script:
  - python goes16_deep_learning_benchmark.py -c benchmark_config_travis.yml
notifications:
  email: true
