log_level: 20
data_path: "/glade/scratch/gwallach/goes16_nc/ABI_patches_20190315_32/" #change to ABI directory
parallel_processes: 35
split_date: "2019-03-16"
conv_net_parameters:
  min_filters: 16
  use_dropout: 0
  dropout_alpha: 0.1
  verbose: 1
  epochs: 20
  learning_rate: 0.0001
  batch_size: 1024
  loss: "binary_crossentropy"
  metrics: ["mean_squared_error", "AUC"]
cpu: 1
num_cpus: 35
single_gpu: 1
multi_gpu: 1
num_gpus: 8
scale_batch_size: 1
dtype: "float32"
random_seed: 4832
out_path: "./benchmark_output_cheyenne"
