log_level: 20
data_path: "data/" #change to ABI directory
parallel_processes: 32
split_date: "2018-05-20"
conv_net_parameters:
  min_filters: 4
  filter_growth_rate: 1.5
  use_dropout: 0
  dropout_alpha: 0.1
  verbose: 1
  epochs: 2
  learning_rate: 0.001
  batch_size: 2048
  loss: "binary_crossentropy"
  metrics: ["mean_squared_error"]
cpu: 1
num_cpus: 1
single_gpu: 1
multi_gpu: 1 #can set to zero
num_gpus: 8
dtype: "float32"
random_seed: 4832
out_path: "./benchmark_output_travis"
