log_level: 20
data_path: "./data"
parallel_processes: 32
split_date: "2018-05-11"
conv_net_parameters:
  min_filters: 32
  use_dropout: 0
  dropout_alpha: 0.1
  verbose: 1
  epochs: 2
  learning_rate: 0.0001
  batch_size: 1024
  loss: "binary_crossentropy"
  metrics: ["mean_squared_error"]
cpu: 1
num_cpus: 30
single_gpu: 1
multi_gpu: 1
num_gpus: 2
dtype: "float32"
random_seed: 4832
out_path: "./output_2"
