log_level: 20
data_path: "/glade/scratch/gwallach/goes16_nc/ABI_patches_20190315_64/" #change to ABI directory
parallel_processes: 32
split_date: "2019-03-15" #changed from 2018-05-20
conv_net_parameters:
  min_filters: 32
  use_dropout: 0
  dropout_alpha: 0.1
  verbose: 1
  epochs: 2 #switch to 10 and see what happens, document difference
  learning_rate: 0.0001
  batch_size: 1024
  loss: "binary_crossentropy"
  metrics: ["mean_squared_error"]
cpu: 0 #can set to zero
num_cpus: 1
single_gpu: 1
multi_gpu: 0 #can set to zero
num_gpus: 8
dtype: "float32"
random_seed: 4832
out_path: "./benchmark_output_final_64"
