batch_loss: 0.1936316043138504
config:
  conv_net_parameters:
    batch_size: 1024
    dropout_alpha: 0.1
    epochs: 1
    learning_rate: 0.0001
    loss: binary_crossentropy
    metrics:
    - mean_squared_error
    min_filters: 32
    use_dropout: 0
    verbose: 1
  cpu: 0
  data_path: /glade/scratch/gwallach/goes16_nc/ABI_patches_20190315_64/
  dtype: float32
  log_level: 20
  multi_gpu: 0
  num_cpus: 1
  num_gpus: 8
  out_path: ./benchmark_output_final_64_1
  parallel_processes: 32
  random_seed: 4832
  single_gpu: 1
  split_date: '2019-03-15'
epoch_loss: 0.15477803849148064
gpu_01_training:
  cpu_memory_percent_max: 8.304833106241098
  cpu_memory_percent_mean: 7.759641729012874
  cpu_memory_percent_median: 8.300542575599884
  cpu_memory_percent_min: 2.049946546914507
  cpu_util_percent_max: 351.8
  cpu_util_percent_mean: 89.47521367521371
  cpu_util_percent_median: 85.2
  cpu_util_percent_min: 0.0
  elapsed_duration: 36.787506704218686
  elapsed_end: 5037122.458259389
  elapsed_start: 5037085.670752685
  epoch_duration: 28.075389654375613
  gpu_memory_total_MiB_0_max: 32480.0
  gpu_memory_total_MiB_0_mean: 32480.0
  gpu_memory_total_MiB_0_median: 32480.0
  gpu_memory_total_MiB_0_min: 32480.0
  gpu_memory_total_MiB_1_max: 32480.0
  gpu_memory_total_MiB_1_mean: 32480.0
  gpu_memory_total_MiB_1_median: 32480.0
  gpu_memory_total_MiB_1_min: 32480.0
  gpu_memory_total_MiB_2_max: 32480.0
  gpu_memory_total_MiB_2_mean: 32480.0
  gpu_memory_total_MiB_2_median: 32480.0
  gpu_memory_total_MiB_2_min: 32480.0
  gpu_memory_total_MiB_3_max: 32480.0
  gpu_memory_total_MiB_3_mean: 32480.0
  gpu_memory_total_MiB_3_median: 32480.0
  gpu_memory_total_MiB_3_min: 32480.0
  gpu_memory_total_MiB_4_max: 32480.0
  gpu_memory_total_MiB_4_mean: 32480.0
  gpu_memory_total_MiB_4_median: 32480.0
  gpu_memory_total_MiB_4_min: 32480.0
  gpu_memory_total_MiB_5_max: 32480.0
  gpu_memory_total_MiB_5_mean: 32480.0
  gpu_memory_total_MiB_5_median: 32480.0
  gpu_memory_total_MiB_5_min: 32480.0
  gpu_memory_total_MiB_6_max: 32480.0
  gpu_memory_total_MiB_6_mean: 32480.0
  gpu_memory_total_MiB_6_median: 32480.0
  gpu_memory_total_MiB_6_min: 32480.0
  gpu_memory_total_MiB_7_max: 32480.0
  gpu_memory_total_MiB_7_mean: 32480.0
  gpu_memory_total_MiB_7_median: 32480.0
  gpu_memory_total_MiB_7_min: 32480.0
  gpu_memory_used_MiB_0_max: 12712.0
  gpu_memory_used_MiB_0_mean: 9116.641025641025
  gpu_memory_used_MiB_0_median: 12712.0
  gpu_memory_used_MiB_0_min: 0.0
  gpu_memory_used_MiB_1_max: 412.0
  gpu_memory_used_MiB_1_mean: 395.54700854700855
  gpu_memory_used_MiB_1_median: 412.0
  gpu_memory_used_MiB_1_min: 0.0
  gpu_memory_used_MiB_2_max: 412.0
  gpu_memory_used_MiB_2_mean: 391.991452991453
  gpu_memory_used_MiB_2_median: 412.0
  gpu_memory_used_MiB_2_min: 0.0
  gpu_memory_used_MiB_3_max: 412.0
  gpu_memory_used_MiB_3_mean: 391.13675213675214
  gpu_memory_used_MiB_3_median: 412.0
  gpu_memory_used_MiB_3_min: 0.0
  gpu_memory_used_MiB_4_max: 412.0
  gpu_memory_used_MiB_4_mean: 389.78632478632477
  gpu_memory_used_MiB_4_median: 412.0
  gpu_memory_used_MiB_4_min: 0.0
  gpu_memory_used_MiB_5_max: 412.0
  gpu_memory_used_MiB_5_mean: 390.982905982906
  gpu_memory_used_MiB_5_median: 412.0
  gpu_memory_used_MiB_5_min: 0.0
  gpu_memory_used_MiB_6_max: 412.0
  gpu_memory_used_MiB_6_mean: 387.78632478632477
  gpu_memory_used_MiB_6_median: 412.0
  gpu_memory_used_MiB_6_min: 0.0
  gpu_memory_used_MiB_7_max: 412.0
  gpu_memory_used_MiB_7_mean: 386.62393162393164
  gpu_memory_used_MiB_7_median: 412.0
  gpu_memory_used_MiB_7_min: 0.0
  gpu_memory_used_percent_0_max: 39.137931034482754
  gpu_memory_used_percent_0_mean: 28.068476064165733
  gpu_memory_used_percent_0_median: 39.137931034482754
  gpu_memory_used_percent_0_min: 0.0
  gpu_memory_used_percent_1_max: 1.2684729064039408
  gpu_memory_used_percent_1_mean: 1.2178171445412824
  gpu_memory_used_percent_1_median: 1.2684729064039408
  gpu_memory_used_percent_1_min: 0.0
  gpu_memory_used_percent_2_max: 1.2684729064039408
  gpu_memory_used_percent_2_mean: 1.2068702370426512
  gpu_memory_used_percent_2_median: 1.2684729064039408
  gpu_memory_used_percent_2_min: 0.0
  gpu_memory_used_percent_3_max: 1.2684729064039408
  gpu_memory_used_percent_3_mean: 1.2042387688939413
  gpu_memory_used_percent_3_median: 1.2684729064039408
  gpu_memory_used_percent_3_min: 0.0
  gpu_memory_used_percent_4_max: 1.2684729064039408
  gpu_memory_used_percent_4_mean: 1.2000810492189806
  gpu_memory_used_percent_4_median: 1.2684729064039408
  gpu_memory_used_percent_4_min: 0.0
  gpu_memory_used_percent_5_max: 1.2684729064039408
  gpu_memory_used_percent_5_mean: 1.2037651046271738
  gpu_memory_used_percent_5_median: 1.2684729064039408
  gpu_memory_used_percent_5_min: 0.0
  gpu_memory_used_percent_6_max: 1.2684729064039408
  gpu_memory_used_percent_6_mean: 1.1939234137510002
  gpu_memory_used_percent_6_median: 1.2684729064039408
  gpu_memory_used_percent_6_min: 0.0
  gpu_memory_used_percent_7_max: 1.2684729064039408
  gpu_memory_used_percent_7_mean: 1.1903446170687555
  gpu_memory_used_percent_7_median: 1.2684729064039408
  gpu_memory_used_percent_7_min: 0.0
  gpu_util_percent_0_max: 100.0
  gpu_util_percent_0_mean: 50.21367521367522
  gpu_util_percent_0_median: 64.0
  gpu_util_percent_0_min: 0.0
  gpu_util_percent_1_max: 8.0
  gpu_util_percent_1_mean: 0.1282051282051282
  gpu_util_percent_1_median: 0.0
  gpu_util_percent_1_min: 0.0
  gpu_util_percent_2_max: 8.0
  gpu_util_percent_2_mean: 0.07692307692307693
  gpu_util_percent_2_median: 0.0
  gpu_util_percent_2_min: 0.0
  gpu_util_percent_3_max: 9.0
  gpu_util_percent_3_mean: 0.1282051282051282
  gpu_util_percent_3_median: 0.0
  gpu_util_percent_3_min: 0.0
  gpu_util_percent_4_max: 9.0
  gpu_util_percent_4_mean: 0.1452991452991453
  gpu_util_percent_4_median: 0.0
  gpu_util_percent_4_min: 0.0
  gpu_util_percent_5_max: 8.0
  gpu_util_percent_5_mean: 0.1452991452991453
  gpu_util_percent_5_median: 0.0
  gpu_util_percent_5_min: 0.0
  gpu_util_percent_6_max: 8.0
  gpu_util_percent_6_mean: 0.1452991452991453
  gpu_util_percent_6_median: 0.0
  gpu_util_percent_6_min: 0.0
  gpu_util_percent_7_max: 9.0
  gpu_util_percent_7_mean: 0.1282051282051282
  gpu_util_percent_7_median: 0.0
  gpu_util_percent_7_min: 0.0
  process_duration: 34.702905503
  process_end: 100.499390728
  process_start: 65.796485225
system:
  cuda_version: '10.1'
  gpu_driver_version: 418.40.04
  gpu_topology: "\t\e[4mGPU0\tGPU1\tGPU2\tGPU3\tGPU4\tGPU5\tGPU6\tGPU7\tmlx5_0\tmlx5_1\t\
    mlx5_2\tmlx5_3\tmlx5_4\tmlx5_5\tCPU Affinity\e[0m\nGPU0\t X \tNV1\tNV1\tNV2\t\
    NV2\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\t0-17,36-53\nGPU1\tNV1\t X\
    \ \tNV2\tNV1\tSYS\tNV2\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\t0-17,36-53\n\
    GPU2\tNV1\tNV2\t X \tNV2\tSYS\tSYS\tNV1\tSYS\tNODE\tNODE\tPIX\tPIX\tSYS\tSYS\t\
    0-17,36-53\nGPU3\tNV2\tNV1\tNV2\t X \tSYS\tSYS\tSYS\tNV1\tNODE\tNODE\tPIX\tPIX\t\
    SYS\tSYS\t0-17,36-53\nGPU4\tNV2\tSYS\tSYS\tSYS\t X \tNV1\tNV1\tNV2\tSYS\tSYS\t\
    SYS\tSYS\tPIX\tPIX\t18-35,54-71\nGPU5\tSYS\tNV2\tSYS\tSYS\tNV1\t X \tNV2\tNV1\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\t18-35,54-71\nGPU6\tSYS\tSYS\tNV1\tSYS\tNV1\tNV2\t\
    \ X \tNV2\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t18-35,54-71\nGPU7\tSYS\tSYS\tSYS\t\
    NV1\tNV2\tNV1\tNV2\t X \tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t18-35,54-71\nmlx5_0\t\
    PIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\t X \tPIX\tNODE\tNODE\tSYS\tSYS\t\nmlx5_1\t\
    PIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\tPIX\t X \tNODE\tNODE\tSYS\tSYS\t\nmlx5_2\t\
    NODE\tNODE\tPIX\tPIX\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t X \tPIX\tSYS\tSYS\t\nmlx5_3\t\
    NODE\tNODE\tPIX\tPIX\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\tPIX\t X \tSYS\tSYS\t\nmlx5_4\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\t X \tPIX\t\nmlx5_5\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\tPIX\t X \t\n\nLegend:\n\
    \n  X    = Self\n  SYS  = Connection traversing PCIe as well as the SMP interconnect\
    \ between NUMA nodes (e.g., QPI/UPI)\n  NODE = Connection traversing PCIe as well\
    \ as the interconnect between PCIe Host Bridges within a NUMA node\n  PHB  = Connection\
    \ traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\n  PXB  =\
    \ Connection traversing multiple PCIe switches (without traversing the PCIe Host\
    \ Bridge)\n  PIX  = Connection traversing a single PCIe switch\n  NV#  = Connection\
    \ traversing a bonded set of # NVLinks\n"
  gpus:
  - 'GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-1bd9ed0e-bc71-d049-98ce-a9a53bc8507c)'
  - 'GPU 1: Tesla V100-SXM2-32GB (UUID: GPU-52514a78-eb66-c1e2-3b83-288cfcd12c99)'
  - 'GPU 2: Tesla V100-SXM2-32GB (UUID: GPU-e43f32c8-388c-b7e7-2367-dc2bd54de77d)'
  - 'GPU 3: Tesla V100-SXM2-32GB (UUID: GPU-41923d9a-e5e2-8f5d-2282-32cc42706676)'
  - 'GPU 4: Tesla V100-SXM2-32GB (UUID: GPU-198f3dd7-fcec-91e4-4883-50317b4218b2)'
  - 'GPU 5: Tesla V100-SXM2-32GB (UUID: GPU-1d0d6b9e-470f-07ca-2931-90a1669913b2)'
  - 'GPU 6: Tesla V100-SXM2-32GB (UUID: GPU-7d3b06e6-2576-ca4e-2065-ba44cffed73e)'
  - 'GPU 7: Tesla V100-SXM2-32GB (UUID: GPU-ef9b63a3-131e-d1ae-7973-52f3851c9fc5)'
  hostname: casper27
  platform: Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
  python_compiler: GCC 7.3.0
  python_version: 3.6.8
  tensorflow_version: 1.13.1
