config:
  conv_net_parameters:
    batch_size: 1024
    dropout_alpha: 0.1
    epochs: 10
    learning_rate: 0.0001
    loss: binary_crossentropy
    metrics:
    - mean_squared_error
    min_filters: 32
    use_dropout: 0
    verbose: 1
  cpu: 0
  data_path: /glade/scratch/gwallach/goes16_nc/ABI_patches_20190315_64/
  dtype: float32
  log_level: 20
  multi_gpu: 0
  num_cpus: 1
  num_gpus: 8
  out_path: ./benchmark_output_final_64
  parallel_processes: 32
  random_seed: 4832
  single_gpu: 1
  split_date: '2019-03-15'
gpu_01_training:
  cpu_memory_percent_max: 8.300407030792819
  cpu_memory_percent_mean: 8.216099708597097
  cpu_memory_percent_median: 8.300407030792819
  cpu_memory_percent_min: 2.04861070442738
  cpu_util_percent_max: 377.2
  cpu_util_percent_mean: 72.97304582210245
  cpu_util_percent_median: 77.4
  cpu_util_percent_min: 0.0
  elapsed_duration: 234.48896360816434
  elapsed_end: 2570551.872489081
  elapsed_start: 2570317.383525473
  epoch_duration: 21.903583009261638
  gpu_memory_total_MiB_0_max: 32480.0
  gpu_memory_total_MiB_0_mean: 32480.0
  gpu_memory_total_MiB_0_median: 32480.0
  gpu_memory_total_MiB_0_min: 32480.0
  gpu_memory_total_MiB_1_max: 32480.0
  gpu_memory_total_MiB_1_mean: 32480.0
  gpu_memory_total_MiB_1_median: 32480.0
  gpu_memory_total_MiB_1_min: 32480.0
  gpu_memory_total_MiB_2_max: 32480.0
  gpu_memory_total_MiB_2_mean: 32480.0
  gpu_memory_total_MiB_2_median: 32480.0
  gpu_memory_total_MiB_2_min: 32480.0
  gpu_memory_total_MiB_3_max: 32480.0
  gpu_memory_total_MiB_3_mean: 32480.0
  gpu_memory_total_MiB_3_median: 32480.0
  gpu_memory_total_MiB_3_min: 32480.0
  gpu_memory_total_MiB_4_max: 32480.0
  gpu_memory_total_MiB_4_mean: 32480.0
  gpu_memory_total_MiB_4_median: 32480.0
  gpu_memory_total_MiB_4_min: 32480.0
  gpu_memory_total_MiB_5_max: 32480.0
  gpu_memory_total_MiB_5_mean: 32480.0
  gpu_memory_total_MiB_5_median: 32480.0
  gpu_memory_total_MiB_5_min: 32480.0
  gpu_memory_total_MiB_6_max: 32480.0
  gpu_memory_total_MiB_6_mean: 32480.0
  gpu_memory_total_MiB_6_median: 32480.0
  gpu_memory_total_MiB_6_min: 32480.0
  gpu_memory_total_MiB_7_max: 32480.0
  gpu_memory_total_MiB_7_mean: 32480.0
  gpu_memory_total_MiB_7_median: 32480.0
  gpu_memory_total_MiB_7_min: 32480.0
  gpu_memory_used_MiB_0_max: 12712.0
  gpu_memory_used_MiB_0_mean: 12167.661725067386
  gpu_memory_used_MiB_0_median: 12712.0
  gpu_memory_used_MiB_0_min: 0.0
  gpu_memory_used_MiB_1_max: 412.0
  gpu_memory_used_MiB_1_mean: 409.0822102425876
  gpu_memory_used_MiB_1_median: 412.0
  gpu_memory_used_MiB_1_min: 0.0
  gpu_memory_used_MiB_2_max: 412.0
  gpu_memory_used_MiB_2_mean: 409.2681940700809
  gpu_memory_used_MiB_2_median: 412.0
  gpu_memory_used_MiB_2_min: 0.0
  gpu_memory_used_MiB_3_max: 412.0
  gpu_memory_used_MiB_3_mean: 409.0741239892183
  gpu_memory_used_MiB_3_median: 412.0
  gpu_memory_used_MiB_3_min: 0.0
  gpu_memory_used_MiB_4_max: 412.0
  gpu_memory_used_MiB_4_mean: 408.57277628032347
  gpu_memory_used_MiB_4_median: 412.0
  gpu_memory_used_MiB_4_min: 0.0
  gpu_memory_used_MiB_5_max: 412.0
  gpu_memory_used_MiB_5_mean: 408.7425876010782
  gpu_memory_used_MiB_5_median: 412.0
  gpu_memory_used_MiB_5_min: 0.0
  gpu_memory_used_MiB_6_max: 412.0
  gpu_memory_used_MiB_6_mean: 408.56469002695417
  gpu_memory_used_MiB_6_median: 412.0
  gpu_memory_used_MiB_6_min: 0.0
  gpu_memory_used_MiB_7_max: 412.0
  gpu_memory_used_MiB_7_mean: 408.0687331536388
  gpu_memory_used_MiB_7_median: 412.0
  gpu_memory_used_MiB_7_min: 0.0
  gpu_memory_used_percent_0_max: 39.137931034482754
  gpu_memory_used_percent_0_mean: 37.462012700330035
  gpu_memory_used_percent_0_median: 39.137931034482754
  gpu_memory_used_percent_0_min: 0.0
  gpu_memory_used_percent_1_max: 1.2684729064039408
  gpu_memory_used_percent_1_mean: 1.2594895635547803
  gpu_memory_used_percent_1_median: 1.2684729064039408
  gpu_memory_used_percent_1_min: 0.0
  gpu_memory_used_percent_2_max: 1.2684729064039408
  gpu_memory_used_percent_2_mean: 1.2600621738611018
  gpu_memory_used_percent_2_median: 1.2684729064039408
  gpu_memory_used_percent_2_min: 0.0
  gpu_memory_used_percent_3_max: 1.2684729064039408
  gpu_memory_used_percent_3_mean: 1.2594646674545054
  gpu_memory_used_percent_3_median: 1.2684729064039408
  gpu_memory_used_percent_3_min: 0.0
  gpu_memory_used_percent_4_max: 1.2684729064039408
  gpu_memory_used_percent_4_mean: 1.2579211092374645
  gpu_memory_used_percent_4_median: 1.2684729064039408
  gpu_memory_used_percent_4_min: 0.0
  gpu_memory_used_percent_5_max: 1.2684729064039408
  gpu_memory_used_percent_5_mean: 1.2584439273432362
  gpu_memory_used_percent_5_median: 1.2684729064039408
  gpu_memory_used_percent_5_min: 0.0
  gpu_memory_used_percent_6_max: 1.2684729064039408
  gpu_memory_used_percent_6_mean: 1.2578962131371896
  gpu_memory_used_percent_6_median: 1.2684729064039408
  gpu_memory_used_percent_6_min: 0.0
  gpu_memory_used_percent_7_max: 1.2684729064039408
  gpu_memory_used_percent_7_mean: 1.2563692523203318
  gpu_memory_used_percent_7_median: 1.2684729064039408
  gpu_memory_used_percent_7_min: 0.0
  gpu_util_percent_0_max: 100.0
  gpu_util_percent_0_mean: 71.4177897574124
  gpu_util_percent_0_median: 71.0
  gpu_util_percent_0_min: 0.0
  gpu_util_percent_1_max: 7.0
  gpu_util_percent_1_mean: 0.018867924528301886
  gpu_util_percent_1_median: 0.0
  gpu_util_percent_1_min: 0.0
  gpu_util_percent_2_max: 9.0
  gpu_util_percent_2_mean: 0.018867924528301886
  gpu_util_percent_2_median: 0.0
  gpu_util_percent_2_min: 0.0
  gpu_util_percent_3_max: 9.0
  gpu_util_percent_3_mean: 0.013477088948787063
  gpu_util_percent_3_median: 0.0
  gpu_util_percent_3_min: 0.0
  gpu_util_percent_4_max: 9.0
  gpu_util_percent_4_mean: 0.02021563342318059
  gpu_util_percent_4_median: 0.0
  gpu_util_percent_4_min: 0.0
  gpu_util_percent_5_max: 9.0
  gpu_util_percent_5_mean: 0.014824797843665768
  gpu_util_percent_5_median: 0.0
  gpu_util_percent_5_min: 0.0
  gpu_util_percent_6_max: 9.0
  gpu_util_percent_6_mean: 0.022911051212938006
  gpu_util_percent_6_median: 0.0
  gpu_util_percent_6_min: 0.0
  gpu_util_percent_7_max: 9.0
  gpu_util_percent_7_mean: 0.01752021563342318
  gpu_util_percent_7_median: 0.0
  gpu_util_percent_7_min: 0.0
  process_duration: 172.21346628999999
  process_end: 240.455444291
  process_start: 68.241978001
system:
  cuda_version: '10.1'
  gpu_driver_version: 418.40.04
  gpu_topology: "\t\e[4mGPU0\tGPU1\tGPU2\tGPU3\tGPU4\tGPU5\tGPU6\tGPU7\tmlx5_0\tmlx5_1\t\
    mlx5_2\tmlx5_3\tmlx5_4\tmlx5_5\tCPU Affinity\e[0m\nGPU0\t X \tNV1\tNV1\tNV2\t\
    NV2\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\t0-17,36-53\nGPU1\tNV1\t X\
    \ \tNV2\tNV1\tSYS\tNV2\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\t0-17,36-53\n\
    GPU2\tNV1\tNV2\t X \tNV2\tSYS\tSYS\tNV1\tSYS\tNODE\tNODE\tPIX\tPIX\tSYS\tSYS\t\
    0-17,36-53\nGPU3\tNV2\tNV1\tNV2\t X \tSYS\tSYS\tSYS\tNV1\tNODE\tNODE\tPIX\tPIX\t\
    SYS\tSYS\t0-17,36-53\nGPU4\tNV2\tSYS\tSYS\tSYS\t X \tNV1\tNV1\tNV2\tSYS\tSYS\t\
    SYS\tSYS\tPIX\tPIX\t18-35,54-71\nGPU5\tSYS\tNV2\tSYS\tSYS\tNV1\t X \tNV2\tNV1\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\t18-35,54-71\nGPU6\tSYS\tSYS\tNV1\tSYS\tNV1\tNV2\t\
    \ X \tNV2\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t18-35,54-71\nGPU7\tSYS\tSYS\tSYS\t\
    NV1\tNV2\tNV1\tNV2\t X \tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t18-35,54-71\nmlx5_0\t\
    PIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\t X \tPIX\tNODE\tNODE\tSYS\tSYS\t\nmlx5_1\t\
    PIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\tPIX\t X \tNODE\tNODE\tSYS\tSYS\t\nmlx5_2\t\
    NODE\tNODE\tPIX\tPIX\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t X \tPIX\tSYS\tSYS\t\nmlx5_3\t\
    NODE\tNODE\tPIX\tPIX\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\tPIX\t X \tSYS\tSYS\t\nmlx5_4\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\t X \tPIX\t\nmlx5_5\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\tPIX\t X \t\n\nLegend:\n\
    \n  X    = Self\n  SYS  = Connection traversing PCIe as well as the SMP interconnect\
    \ between NUMA nodes (e.g., QPI/UPI)\n  NODE = Connection traversing PCIe as well\
    \ as the interconnect between PCIe Host Bridges within a NUMA node\n  PHB  = Connection\
    \ traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\n  PXB  =\
    \ Connection traversing multiple PCIe switches (without traversing the PCIe Host\
    \ Bridge)\n  PIX  = Connection traversing a single PCIe switch\n  NV#  = Connection\
    \ traversing a bonded set of # NVLinks\n"
  gpus:
  - 'GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-49e974e5-2622-0ae0-3d8b-55248d31364a)'
  - 'GPU 1: Tesla V100-SXM2-32GB (UUID: GPU-d4a9989b-9ee6-b6eb-b261-429baf332798)'
  - 'GPU 2: Tesla V100-SXM2-32GB (UUID: GPU-708dcfc2-d368-c64d-0a6d-65b1bdf92a6d)'
  - 'GPU 3: Tesla V100-SXM2-32GB (UUID: GPU-8cfef19b-3b4d-7dc0-ace8-c7ae451ebf27)'
  - 'GPU 4: Tesla V100-SXM2-32GB (UUID: GPU-3b81ff7d-20f5-31d0-d66e-e4fa204811db)'
  - 'GPU 5: Tesla V100-SXM2-32GB (UUID: GPU-83532bb9-d74d-a762-8512-506bc499cc39)'
  - 'GPU 6: Tesla V100-SXM2-32GB (UUID: GPU-cf517236-f579-2084-5ff7-4cc3e3b43f00)'
  - 'GPU 7: Tesla V100-SXM2-32GB (UUID: GPU-5f28da95-169c-1d2e-7580-2486ba9c4c97)'
  hostname: casper24
  platform: Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
  python_compiler: GCC 7.3.0
  python_version: 3.6.8
  tensorflow_version: 1.13.1
