glm:
  glm_path: "/glade/p/cisl/aiml/gwallach/goes16_nc/GLM-L2_LCFA/" # Path to GLM netCDF files
  grid_path: "/glade/p/cisl/aiml/gwallach/goes16_nc/GLM_grids/"  # Path to output gridded GLM netCDF files
  start_date: "2018-04-01" # First date to perform gridding
  end_date: "2018-06-06" # Last date to perform gridding (inclusive)
  file_freq: "1D" # How often to write separate netCDF files
  grid_freq: "20Min" # Aggregation period for each gridded time step
  grid_proj_params: # Projection definition for Pyproj (PROJ4 keywords)
    proj: "lcc"
    lon_0: -90.0
    lat_0: 39.0
    lat_1: 25.0
    lat_2: 50.0
  dx_km: 16.0 # Horizontal grid spacing in km
  x_extent_km: 1024.0 # west-east extent of grid in km
  y_extent_km: 2048.0 # south-north extent of grid in km
abi:
  abi_path: "/glade/p/cisl/aiml/gwallach/goes16_nc/ABI-L1b_conus/"
  patch_path: "/glade/p/cisl/aiml/gwallach/goes16_nc/ABI_patches_20190315/"
  glm_grid_path: "/glade/p/cisl/aiml/gwallach/goes16_nc/GLM_grids/"
  start_date: "2018-04-02"
  end_date: "2018-06-06"
  bands: [8, 9, 10, 14]
  file_freq: "1D"
  lead_time: "20Min"
  patch_x_length_pixels: 64
  patch_y_length_pixels: 64
  samples_per_time: 20
  time_range_minutes: 4
  bt: 1
