batch_loss: 0.11059875786304474
config:
  conv_net_parameters:
    batch_size: 1024
    dropout_alpha: 0.1
    epochs: 10
    learning_rate: 0.0001
    loss: binary_crossentropy
    metrics:
    - mean_squared_error
    min_filters: 32
    use_dropout: 0
    verbose: 1
  cpu: 0
  data_path: /glade/scratch/gwallach/goes16_nc/ABI_patches_20190315_32/
  dtype: float32
  log_level: 20
  multi_gpu: 0
  num_cpus: 1
  num_gpus: 8
  out_path: ./benchmark_output_final_32_10
  parallel_processes: 32
  random_seed: 4832
  single_gpu: 1
  split_date: '2019-03-15'
epoch_loss: 0.11777999118992324
gpu_01_training:
  cpu_memory_percent_max: 6.584672470781316
  cpu_memory_percent_mean: 6.3166998585679375
  cpu_memory_percent_median: 6.584672470781316
  cpu_memory_percent_min: 0.6426457887292577
  cpu_util_percent_max: 401.4
  cpu_util_percent_mean: 86.57447916666665
  cpu_util_percent_median: 89.05
  cpu_util_percent_min: 0.0
  elapsed_duration: 57.849509079009295
  elapsed_end: 5083733.535697279
  elapsed_start: 5083675.6861882
  epoch_duration: 4.614684962667525
  gpu_memory_total_MiB_0_max: 32480.0
  gpu_memory_total_MiB_0_mean: 32480.0
  gpu_memory_total_MiB_0_median: 32480.0
  gpu_memory_total_MiB_0_min: 32480.0
  gpu_memory_total_MiB_1_max: 32480.0
  gpu_memory_total_MiB_1_mean: 32480.0
  gpu_memory_total_MiB_1_median: 32480.0
  gpu_memory_total_MiB_1_min: 32480.0
  gpu_memory_total_MiB_2_max: 32480.0
  gpu_memory_total_MiB_2_mean: 32480.0
  gpu_memory_total_MiB_2_median: 32480.0
  gpu_memory_total_MiB_2_min: 32480.0
  gpu_memory_total_MiB_3_max: 32480.0
  gpu_memory_total_MiB_3_mean: 32480.0
  gpu_memory_total_MiB_3_median: 32480.0
  gpu_memory_total_MiB_3_min: 32480.0
  gpu_memory_total_MiB_4_max: 32480.0
  gpu_memory_total_MiB_4_mean: 32480.0
  gpu_memory_total_MiB_4_median: 32480.0
  gpu_memory_total_MiB_4_min: 32480.0
  gpu_memory_total_MiB_5_max: 32480.0
  gpu_memory_total_MiB_5_mean: 32480.0
  gpu_memory_total_MiB_5_median: 32480.0
  gpu_memory_total_MiB_5_min: 32480.0
  gpu_memory_total_MiB_6_max: 32480.0
  gpu_memory_total_MiB_6_mean: 32480.0
  gpu_memory_total_MiB_6_median: 32480.0
  gpu_memory_total_MiB_6_min: 32480.0
  gpu_memory_total_MiB_7_max: 32480.0
  gpu_memory_total_MiB_7_mean: 32480.0
  gpu_memory_total_MiB_7_median: 32480.0
  gpu_memory_total_MiB_7_min: 32480.0
  gpu_memory_used_MiB_0_max: 9414.0
  gpu_memory_used_MiB_0_mean: 7940.046875
  gpu_memory_used_MiB_0_median: 9414.0
  gpu_memory_used_MiB_0_min: 0.0
  gpu_memory_used_MiB_1_max: 412.0
  gpu_memory_used_MiB_1_mean: 400.484375
  gpu_memory_used_MiB_1_median: 412.0
  gpu_memory_used_MiB_1_min: 0.0
  gpu_memory_used_MiB_2_max: 412.0
  gpu_memory_used_MiB_2_mean: 399.7447916666667
  gpu_memory_used_MiB_2_median: 412.0
  gpu_memory_used_MiB_2_min: 0.0
  gpu_memory_used_MiB_3_max: 412.0
  gpu_memory_used_MiB_3_mean: 399.0885416666667
  gpu_memory_used_MiB_3_median: 412.0
  gpu_memory_used_MiB_3_min: 0.0
  gpu_memory_used_MiB_4_max: 412.0
  gpu_memory_used_MiB_4_mean: 399.828125
  gpu_memory_used_MiB_4_median: 412.0
  gpu_memory_used_MiB_4_min: 0.0
  gpu_memory_used_MiB_5_max: 412.0
  gpu_memory_used_MiB_5_mean: 397.828125
  gpu_memory_used_MiB_5_median: 412.0
  gpu_memory_used_MiB_5_min: 0.0
  gpu_memory_used_MiB_6_max: 412.0
  gpu_memory_used_MiB_6_mean: 398.421875
  gpu_memory_used_MiB_6_median: 412.0
  gpu_memory_used_MiB_6_min: 0.0
  gpu_memory_used_MiB_7_max: 412.0
  gpu_memory_used_MiB_7_mean: 396.3854166666667
  gpu_memory_used_MiB_7_median: 412.0
  gpu_memory_used_MiB_7_min: 0.0
  gpu_memory_used_percent_0_max: 28.98399014778325
  gpu_memory_used_percent_0_mean: 24.44595712746302
  gpu_memory_used_percent_0_median: 28.98399014778325
  gpu_memory_used_percent_0_min: 0.0
  gpu_memory_used_percent_1_max: 1.2684729064039408
  gpu_memory_used_percent_1_mean: 1.233018395935956
  gpu_memory_used_percent_1_median: 1.2684729064039408
  gpu_memory_used_percent_1_min: 0.0
  gpu_memory_used_percent_2_max: 1.2684729064039408
  gpu_memory_used_percent_2_mean: 1.2307413536535259
  gpu_memory_used_percent_2_median: 1.2684729064039408
  gpu_memory_used_percent_2_min: 0.0
  gpu_memory_used_percent_3_max: 1.2684729064039408
  gpu_memory_used_percent_3_mean: 1.2287208795155948
  gpu_memory_used_percent_3_median: 1.2684729064039408
  gpu_memory_used_percent_3_min: 0.0
  gpu_memory_used_percent_4_max: 1.2684729064039408
  gpu_memory_used_percent_4_mean: 1.230997921798025
  gpu_memory_used_percent_4_median: 1.2684729064039408
  gpu_memory_used_percent_4_min: 0.0
  gpu_memory_used_percent_5_max: 1.2684729064039408
  gpu_memory_used_percent_5_mean: 1.2248402863300447
  gpu_memory_used_percent_5_median: 1.2684729064039408
  gpu_memory_used_percent_5_min: 0.0
  gpu_memory_used_percent_6_max: 1.2684729064039408
  gpu_memory_used_percent_6_mean: 1.2266683343596012
  gpu_memory_used_percent_6_median: 1.2684729064039408
  gpu_memory_used_percent_6_min: 0.0
  gpu_memory_used_percent_7_max: 1.2684729064039408
  gpu_memory_used_percent_7_mean: 1.2203984503284027
  gpu_memory_used_percent_7_median: 1.2684729064039408
  gpu_memory_used_percent_7_min: 0.0
  gpu_util_percent_0_max: 94.0
  gpu_util_percent_0_mean: 61.28125
  gpu_util_percent_0_median: 76.0
  gpu_util_percent_0_min: 0.0
  gpu_util_percent_1_max: 8.0
  gpu_util_percent_1_mean: 0.057291666666666664
  gpu_util_percent_1_median: 0.0
  gpu_util_percent_1_min: 0.0
  gpu_util_percent_2_max: 8.0
  gpu_util_percent_2_mean: 0.078125
  gpu_util_percent_2_median: 0.0
  gpu_util_percent_2_min: 0.0
  gpu_util_percent_3_max: 9.0
  gpu_util_percent_3_mean: 0.09375
  gpu_util_percent_3_median: 0.0
  gpu_util_percent_3_min: 0.0
  gpu_util_percent_4_max: 8.0
  gpu_util_percent_4_mean: 0.078125
  gpu_util_percent_4_median: 0.0
  gpu_util_percent_4_min: 0.0
  gpu_util_percent_5_max: 9.0
  gpu_util_percent_5_mean: 0.09375
  gpu_util_percent_5_median: 0.0
  gpu_util_percent_5_min: 0.0
  gpu_util_percent_6_max: 7.0
  gpu_util_percent_6_mean: 0.041666666666666664
  gpu_util_percent_6_median: 0.0
  gpu_util_percent_6_min: 0.0
  gpu_util_percent_7_max: 8.0
  gpu_util_percent_7_mean: 0.057291666666666664
  gpu_util_percent_7_median: 0.0
  gpu_util_percent_7_min: 0.0
  process_duration: 51.443240986
  process_end: 69.091606227
  process_start: 17.648365241
system:
  cuda_version: '10.1'
  gpu_driver_version: 418.40.04
  gpu_topology: "\t\e[4mGPU0\tGPU1\tGPU2\tGPU3\tGPU4\tGPU5\tGPU6\tGPU7\tmlx5_0\tmlx5_1\t\
    mlx5_2\tmlx5_3\tmlx5_4\tmlx5_5\tCPU Affinity\e[0m\nGPU0\t X \tNV1\tNV1\tNV2\t\
    NV2\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\t0-17,36-53\nGPU1\tNV1\t X\
    \ \tNV2\tNV1\tSYS\tNV2\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\t0-17,36-53\n\
    GPU2\tNV1\tNV2\t X \tNV2\tSYS\tSYS\tNV1\tSYS\tNODE\tNODE\tPIX\tPIX\tSYS\tSYS\t\
    0-17,36-53\nGPU3\tNV2\tNV1\tNV2\t X \tSYS\tSYS\tSYS\tNV1\tNODE\tNODE\tPIX\tPIX\t\
    SYS\tSYS\t0-17,36-53\nGPU4\tNV2\tSYS\tSYS\tSYS\t X \tNV1\tNV1\tNV2\tSYS\tSYS\t\
    SYS\tSYS\tPIX\tPIX\t18-35,54-71\nGPU5\tSYS\tNV2\tSYS\tSYS\tNV1\t X \tNV2\tNV1\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\t18-35,54-71\nGPU6\tSYS\tSYS\tNV1\tSYS\tNV1\tNV2\t\
    \ X \tNV2\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t18-35,54-71\nGPU7\tSYS\tSYS\tSYS\t\
    NV1\tNV2\tNV1\tNV2\t X \tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t18-35,54-71\nmlx5_0\t\
    PIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\t X \tPIX\tNODE\tNODE\tSYS\tSYS\t\nmlx5_1\t\
    PIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\tPIX\t X \tNODE\tNODE\tSYS\tSYS\t\nmlx5_2\t\
    NODE\tNODE\tPIX\tPIX\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\t X \tPIX\tSYS\tSYS\t\nmlx5_3\t\
    NODE\tNODE\tPIX\tPIX\tSYS\tSYS\tSYS\tSYS\tNODE\tNODE\tPIX\t X \tSYS\tSYS\t\nmlx5_4\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\t X \tPIX\t\nmlx5_5\t\
    SYS\tSYS\tSYS\tSYS\tPIX\tPIX\tNODE\tNODE\tSYS\tSYS\tSYS\tSYS\tPIX\t X \t\n\nLegend:\n\
    \n  X    = Self\n  SYS  = Connection traversing PCIe as well as the SMP interconnect\
    \ between NUMA nodes (e.g., QPI/UPI)\n  NODE = Connection traversing PCIe as well\
    \ as the interconnect between PCIe Host Bridges within a NUMA node\n  PHB  = Connection\
    \ traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\n  PXB  =\
    \ Connection traversing multiple PCIe switches (without traversing the PCIe Host\
    \ Bridge)\n  PIX  = Connection traversing a single PCIe switch\n  NV#  = Connection\
    \ traversing a bonded set of # NVLinks\n"
  gpus:
  - 'GPU 0: Tesla V100-SXM2-32GB (UUID: GPU-83a80b5c-fa0c-f77c-1589-68aace52b5de)'
  - 'GPU 1: Tesla V100-SXM2-32GB (UUID: GPU-6783ace8-3af4-aaca-406e-cacd70eae7e6)'
  - 'GPU 2: Tesla V100-SXM2-32GB (UUID: GPU-7b85bb28-2998-ab2b-fec6-e8c2c06971a7)'
  - 'GPU 3: Tesla V100-SXM2-32GB (UUID: GPU-a2874c56-e23b-a249-6222-2c7205360aac)'
  - 'GPU 4: Tesla V100-SXM2-32GB (UUID: GPU-f86ee2bd-420a-f7da-f0b9-041b3b9daa2e)'
  - 'GPU 5: Tesla V100-SXM2-32GB (UUID: GPU-cb7d8369-62e2-44a2-03e0-461669121523)'
  - 'GPU 6: Tesla V100-SXM2-32GB (UUID: GPU-a4d69e0f-be59-8899-2cc0-0f26feeb18f1)'
  - 'GPU 7: Tesla V100-SXM2-32GB (UUID: GPU-1a7d80ea-0472-48de-b771-0d5821373239)'
  hostname: casper08
  platform: Linux-3.10.0-693.21.1.el7.x86_64-x86_64-with-centos-7.4.1708-Core
  python_compiler: GCC 7.3.0
  python_version: 3.6.8
  tensorflow_version: 1.13.1
